# docker-compose.yml.development
version: '3.8'
services:
  database:
    platform: linux/x86_64 # for m1 mac error
    image: mysql:latest
    container_name: demo-conversion-tracker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
